apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-hello-node-deployment
  labels:
    app: kub-hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-hello-node
  template:
    metadata:
      labels:
        app: kub-hello-node
    spec:
      containers:
      - name: kub-hello-node
        image: phuhung273/kub-hello-node:latest
        ports:
        - containerPort: 8080
