apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: phuhung273/kub-hello-networking-user:latest
          env:
            - name: AUTH_ADDRESS
              value: auth-service