apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: phuhung273/kub-hello-data:latest
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          env:
          # # get single value from config
          #   - name: STORY_DIR
          #     valueFrom:
          #       configMapKeyRef:
          #         name: story-config
          #         key: STORY_DIR
          #   - name: OWNER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: story-config
          #         key: OWNER
          # get all value from config
          envFrom:
            - configMapRef:
                name: story-config
      volumes:
      - name: story-volume
        # emptyDir: {} # Lifecycle attached to Pod
        persistentVolumeClaim:
          claimName: story-pvc